const tool = (name, kind = "app", source = "detected") => ({
  name,
  kind,
  source,
});

export const MAHID_TOOL_GROUPS = [
  {
    name: "AI & agents",
    tools: [
      tool("Codex", "cli"),
      tool("Claude"),
      tool("Cursor"),
      tool("ChatGPT"),
      tool("Ollama", "cli"),
    ],
  },
  {
    name: "Build",
    tools: [
      tool("Zed"),
      tool("GitHub", "cli"),
      tool("Warp"),
      tool("Homebrew", "cli"),
      tool("Xcode"),
    ],
  },
  {
    name: "Design",
    tools: [
      tool("Figma"),
      tool("Blender"),
      tool("Fusion"),
      tool("Screen Studio"),
    ],
  },
  {
    name: "Operate",
    tools: [
      tool("Linear"),
      tool("Notion"),
      tool("Slack"),
      tool("Superhuman"),
      tool("WhatsApp"),
      tool("X", "app", "manual"),
    ],
  },
  {
    name: "Data & cloud",
    tools: [
      tool("Python", "cli"),
      tool("Node.js", "cli"),
      tool("BigQuery", "cli"),
      tool("Cloudflare", "cli"),
      tool("Docker", "cli"),
    ],
  },
];

export const BUILDERS = [
  {
    slug: "mahidalhan",
    name: "Mahid",
    handle: "@mahidalhan",
    xHandle: "@mahidalhan",
    xUrl: "https://x.com/mahidalhan",
    role: "Physical AI builder",
    count: 135,
    detectedCount: 134,
    manualCount: 1,
    categories: 20,
    tags: ["AI", "Hardware", "Developer tools", "Design", "Data"],
    monogram: "M",
    motif: "m",
    demo: false,
    tools: MAHID_TOOL_GROUPS,
    signals: [
      "AI-assisted builder",
      "Polyglot builder",
      "Cloud & infrastructure",
      "Hardware builder",
    ],
  },
  {
    slug: "maya-demo",
    name: "Maya Chen",
    handle: "@mayachen",
    role: "Product designer & design systems",
    count: 97,
    tags: ["Design", "Developer tools"],
    monogram: "MC",
    motif: "split",
    demo: true,
    toolNames: ["Figma", "Notion", "Linear", "Slack", "GitHub", "Cursor"],
  },
  {
    slug: "owen-demo",
    name: "Owen Park",
    handle: "@owenpark",
    role: "Indie developer & automation tinkerer",
    count: 86,
    tags: ["AI", "Developer tools"],
    monogram: "OP",
    motif: "circle",
    demo: true,
    toolNames: ["Cursor", "Zed", "GitHub", "Linear", "Notion", "Codex"],
  },
  {
    slug: "rina-demo",
    name: "Rina Bell",
    handle: "@rinabell",
    role: "Data engineer & analytics nerd",
    count: 72,
    tags: ["Data", "Developer tools"],
    monogram: "RB",
    motif: "diamond",
    demo: true,
    toolNames: ["Zed", "Python", "dbt", "BigQuery", "Notion", "GitHub"],
  },
  {
    slug: "eliot-demo",
    name: "Eliot Vega",
    handle: "@eliotvega",
    role: "Hardware hacker & 3D builder",
    count: 68,
    tags: ["Hardware", "Design"],
    monogram: "EV",
    motif: "peak",
    demo: true,
    toolNames: ["Blender", "Fusion", "KiCad", "GitHub", "Notion", "Zed"],
  },
  {
    slug: "zoe-demo",
    name: "Zoe Kim",
    handle: "@zoekim",
    role: "AI researcher & prototyper",
    count: 61,
    tags: ["AI", "Data"],
    monogram: "ZK",
    motif: "ring",
    demo: true,
    toolNames: ["Codex", "Python", "Jupyter", "Notion", "GitHub", "Linear"],
  },
];

export const FILTERS = [
  "All",
  "AI",
  "Design",
  "Hardware",
  "Data",
  "Developer tools",
];

export const HERO_LAYERS = [
  "CODEX",
  "CURSOR",
  "FIGMA",
  "LINEAR",
  "NOTION",
  "GITHUB",
  "SLACK",
  "X · MANUAL",
];
